#include "peer.h"
#include <stdint.h>
static int wait_socket(SOCKET s,int wr,int ms){fd_set f;FD_ZERO(&f);FD_SET(s,&f);struct timeval tv={ms/1000,(ms%1000)*1000};return select(0,wr?NULL:&f,wr?&f:NULL,NULL,&tv)>0;}
static int recv_all(SOCKET s,void*b,size_t n){size_t o=0;unsigned char*p=b;while(o<n){if(!wait_socket(s,0,15000))return 0;int r=recv(s,(char*)p+o,(int)(n-o),0);if(r<=0)return 0;o+=r;}return 1;}
static int send_all(SOCKET s,const void*b,size_t n){size_t o=0;const unsigned char*p=b;while(o<n){if(!wait_socket(s,1,15000))return 0;int r=send(s,(const char*)p+o,(int)(n-o),0);if(r<=0)return 0;o+=r;}return 1;}
static int msg(SOCKET s,uint8_t id,const void*p,size_t n){if(n>16*1024*1024-1)return 0;uint32_t l=htonl((uint32_t)n+1);unsigned char h[5];memcpy(h,&l,4);h[4]=id;return send_all(s,h,5)&&(!n||send_all(s,p,n));}
static int recv_msg(SOCKET s,unsigned char**out,uint32_t*len){unsigned char h[4];if(!recv_all(s,h,4))return 0;uint32_t n=ntohl(*(uint32_t*)h);if(n==0){*out=NULL;*len=0;return 1;}if(n>16*1024*1024)return 0;unsigned char*p=malloc(n);if(!p)return 0;if(!recv_all(s,p,n)){free(p);return 0;}*out=p;*len=n;return 1;}
static int have_piece(const unsigned char*b,size_t n,size_t piece){size_t byte=piece/8;if(byte>=n)return 0;return (b[byte]&(unsigned char)(0x80u>>(piece%8)))!=0;}
static int request_block(SOCKET s,uint32_t piece,uint32_t off,uint32_t len,unsigned char*dst){unsigned char p[12];uint32_t x=htonl(piece);memcpy(p,&x,4);x=htonl(off);memcpy(p+4,&x,4);x=htonl(len);memcpy(p+8,&x,4);if(!msg(s,6,p,12))return 0;for(;;){unsigned char*m=NULL;uint32_t ml=0;if(!recv_msg(s,&m,&ml))return 0;if(ml==0)continue;uint8_t id=m[0];if(id==0){free(m);continue;}if(id==7&&ml>=9){uint32_t pi=ntohl(*(uint32_t*)(m+1)),po=ntohl(*(uint32_t*)(m+5));if(pi==piece&&po==off){size_t got=ml-9;int ok=got==len;if(ok)memcpy(dst,m+9,len);free(m);return ok;}}free(m);}}
int peer_download_piece(const Torrent*t,const PeerAddress*p,const unsigned char id[20],size_t piece,unsigned char**out,size_t*n){
    *out=NULL;*n=0;if(piece>=torrent_piece_count(t))return 0;SOCKET s=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(s==INVALID_SOCKET)return 0;struct sockaddr_in a={0};a.sin_family=AF_INET;a.sin_port=htons(p->port);if(inet_pton(AF_INET,p->ip,&a.sin_addr)!=1){closesocket(s);return 0;}
    u_long nb=1;ioctlsocket(s,FIONBIO,&nb);int cr=connect(s,(struct sockaddr*)&a,sizeof(a));int ce=WSAGetLastError();if(cr==SOCKET_ERROR&&ce!=WSAEWOULDBLOCK&&ce!=WSAEINPROGRESS){closesocket(s);return 0;}if(!wait_socket(s,1,10000)){closesocket(s);return 0;}int err=0,el=sizeof(err);getsockopt(s,SOL_SOCKET,SO_ERROR,(char*)&err,&el);if(err){closesocket(s);return 0;}nb=0;ioctlsocket(s,FIONBIO,&nb);
    unsigned char h[68]={19};memcpy(h+1,"BitTorrent protocol",19);memcpy(h+28,t->info_hash,20);memcpy(h+48,id,20);if(!send_all(s,h,68)||!recv_all(s,h,68)||memcmp(h+28,t->info_hash,20)){closesocket(s);return 0;}
    if(!msg(s,2,NULL,0)){closesocket(s);return 0;}int unchoked=0,known_have=0,piece_available=0;unsigned char*bitfield=NULL;size_t bitfield_len=0;
    for(int loops=0;loops<32&&!unchoked;loops++){unsigned char*m=NULL;uint32_t ml=0;if(!recv_msg(s,&m,&ml)){free(bitfield);closesocket(s);return 0;}if(!ml)continue;switch(m[0]){case 0:unchoked=0;break;case 1:unchoked=1;break;case 4:if(ml>=5&&ntohl(*(uint32_t*)(m+1))==piece)piece_available=1;known_have=1;break;case 5:free(bitfield);bitfield_len=ml-1;bitfield=malloc(bitfield_len);if(bitfield){memcpy(bitfield,m+1,bitfield_len);piece_available=have_piece(bitfield,bitfield_len,piece);known_have=1;}break;default:break;}free(m);}
    if(!unchoked||(known_have&&!piece_available)){free(bitfield);closesocket(s);return 0;}free(bitfield);uint64_t z=torrent_piece_length(t,piece);unsigned char*d=malloc((size_t)z);if(!d){closesocket(s);return 0;}for(uint64_t off=0;off<z;off+=BLOCK_SIZE){uint32_t len=(uint32_t)((z-off)>BLOCK_SIZE?BLOCK_SIZE:z-off);if(!request_block(s,(uint32_t)piece,(uint32_t)off,len,d+off)){free(d);closesocket(s);return 0;}}closesocket(s);if(!torrent_verify_piece(t,piece,d,(size_t)z)){free(d);return 0;}*out=d;*n=(size_t)z;return 1;
}
